### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by riiraty** [Meemeimei/Keskustelufoorumi#9]
_Projekti ladattu lauantaina 25.4.-20 klo 10:22_

### Kommentteja ja pieniä korjausehdotuksia

* Valitettavasti ulkoasu oli katselmointihetkellä särki, kuten README:ssa sanoitkin.

* Rekisteröityminen toimii, virheviestit järkeviä. Hyvä lisä, että salasanan vahvistuksen validointi näkyy reaaliajassa. 

* Kirjatumisessa on ongelma, jos sovelluksen käynnistää uusiksi, niin kirjautuminen ei onnistu. Ilmeisesti ```str(hash(form.password.data))``` ei hashaa samalla tavoin joka kerta. 

* Käyttäjä pystyy poistamaan muita käyttäjiä ilman admin-roolia:
  _/Sovellus/administration/administrationController.py_ funktio ```deleteUser()``` ei tarkista onko current_user admin.

* Admin-toimintojen ohjaimet näkyy käyttäjälle, jolla ei ole admin-oikeuksia. 
  ``` {% if current_user.is_admin %} ```
  on aina totta, koska User.admin ei ole ikinä None vaan True/1 tai False/0
  ``` {% if current_user.is_admin  == True %} ```
  korjaa tilanteen.
   
* Jos käyttäjä poistaa itsensä, niin sovellus kaatuu. Tämän voisi kiertää esim tarkistamalla onko funktion ```deleteUser()``` attribuuttina annettu ```userId``` ```current_user.id```, ja tarvittaessa kirjaamalla käyttäjä ulos:
  ```
  if (userId == current_user.id):
      logout_user()
      return redirect("/")
  ```
  Tai vaikka estämällä itsensä poistamisen kokonaan. 

* Alueiden ja aloitusten poistaminen toimii vain admin-käyttäjällä, virheviesit järkeviä. 

* Uuden alueen luominen, aloituksen tekeminen ja kommentointi toimii kuten kuvattu.

* Uuden ryhmän lisääminen ei onnistunut, nappi on disabled, vaikka fieldiin kirjoittaisi jotain. En löytänyt kunnon selitystä tälle, alueiden kohdalla vastaava toteutus toimii normaalisti.

* Lisäsin uuden  ryhmän käsin, siihen näytti pääsevän käsiksi kuka tahansa. 
  _/Sovellus/groups/groupController.py_ rivi 33 muotoon
    ```groupuser = Groupuser.query.filter_by(user_id=current_user.id, group_id=group.id).first()```
  niin sitä seuraava ehtolause toimii. Nyt siitä siis puuttui ```.first()```

* WTForms:illa tehty syötteille validoinnit, mutta niitä ei tarkasteta, esim:

   _/Sovellus/auth/forms.py_ määritelty LoginFormin kenttien pituudeksi _min=2_

  _Sovellus/user/userController.py_ tiedoston funktioon _register()_ käyttää 
  LoginFormia, siihen voi lisätä esim ehdon:

  ```
  if not form.validate():
      return render_template("login/register.html", form= form)
  ```
  Jolloin käyttäjälle renderöidään uudestaan näkyviin lomake, käyttäjän aiemmin täyttämän lomakkeen pohjalta. Virheviestit löytyvy ```form``` muuttujasta ```errors```, ne voi esim loopata listaksi templateen _/login/register.html_.

  Kurssimateriaalin Osa 3, alaluku 1.5 on kokonainen esimerkki toteutuksesta.
  Dokumentaatio löytyy [https://wtforms.readthedocs.io/en/stable/validators.html](https://wtforms.readthedocs.io/en/stable/validators.html)

* Kansioiden _/Sovellus/users_ ja _/Sovellus/auth_ ja _/Sovellus/administration_ sisällöt näyttävät kaikki käsittelevän käyttäjää, onko kolmeen kansioon jako tarpeen?

* _index.html_ -tiedostoissa on irtonaisia, for loopeissa tuotettuja rivejä, jotka eivät ole taulun sisällä. 
  Esim. _/area/index.html_ postausten for loop tagien ```<table></table>``` sisään.

Sovellus on edennyt pitkälle, ja pienillä korjauksilla kaikki määritellyt toiminnot alkaa olla kunnossa. Muuttujien nimeämiset yms. tehty hyvin, koodi on helppolukuista ilman kommenttejakin. Tsemppiä loppurutistukseen!

**Comment by Meemeimei** [comment]
Moi,

Kiitokset laadukkaasta palautteesta. Hyviä kommentteja ja niissä mainitut ongelmat on nyt korjattu.
